### ISSUE TITLE
Trained Models

### ISSUE THREAD

**Issue by aryan-f** [alilajevardi/Embedded-Block-Residual-Network#1]
Could you please share the trained models? I was trying to train them on my own system but it keeps crashing cause it fills up the RAM quickly. I greatly appreciate it.

**Comment by alilajevardi** [comment]
> Could you please share the trained models? I was trying to train them on my own system but it keeps crashing cause it fills up the RAM quickly. I greatly appreciate it.

Unfortunately, the model is very heavy and need a high capacity RAM. 
In the original paper, they mentioned that the learning parameters for model with 10 BRMs is less that 10 million, however my implement by TensorFlow shows that only 3 BRMs produces more than 80 million parameters. I sent them an email to ask about this big difference with what they reported, but long pause no response.
With 3 BRMs the training result is not good and not same as what they reported.

**Comment by aryan-f** [comment]
That's unfortunate.
Do you have any estimates of the required resources for training an exact replica of the model in the paper? I might be able to get a session on AWS or sth. Also, the notebook you've prepared, is the configuration different from the paper? Or do I have to just load it on the server and let it run?

**Comment by alilajevardi** [comment]
I used a Quadro RTX8000 that equipped with 48GB of dedicated RAM.
I tried to implement all settings, parameters and initialization as reported in the original paper.

**Comment by aryan-f** [comment]
Alright, thanks! I'll see what I can do and if I manage to train it, I'll send it to you so you can share it along with the code.
