### ISSUE TITLE
About psnr

### ISSUE THREAD

**Issue by zhaowenlovehome** [alilajevardi/Embedded-Block-Residual-Network#3]
I'm interseting your job, can you share the psnr/ssim

**Comment by alilajevardi** [comment]
Hi Zhaowen,
I followed the paper for implementing the network, however its performance was not the same as reported in the paper.
I think there is something wrong with the paper, because the number of parameters are very big ~90 million.
So it is not easy to train such heavy model.

**Comment by alilajevardi** [comment]
closed
