### ISSUE TITLE
Hello, I trained an X4 model according to your code, but the effect is much worse than what you showed on jupyter. Can you tell me your training settings

### ISSUE THREAD

**Issue by Rouchestand** [alilajevardi/Embedded-Block-Residual-Network#6]

**Comment by alilajevardi** [comment]
Sure
My settings are all in the Jupyter file. Send me your work, I will check it for you.
If you check reported SIM metrics you can see that the network is not as good as what reported in the original paper. The original paper shows fake results.

**Comment by Rouchestand** [comment]
The training model file is too heavy to upload. I trained according to the jupyter file. SSIM is slightly lower than that shown on jupyter. Sincerely thank you for your work.

**Comment by alilajevardi** [comment]
Thanks
